alter table EIS_ANALYSIS_FORM add constraint FK_EIS_ANALYSIS_FORM_ON_DEFECT_TYPE foreign key (DEFECT_TYPE_ID) references EIS_DEFECT_TYPE(ID);
create index IDX_EIS_ANALYSIS_FORM_ON_DEFECT_TYPE on EIS_ANALYSIS_FORM (DEFECT_TYPE_ID);
