alter table EIS_TECHNICAL_FORM add constraint FK_EIS_TECHNICAL_FORM_ON_EXECUTOR_S1 foreign key (EXECUTOR_S1_ID) references EIS_DIVISION_INDEX(ID);
create index IDX_EIS_TECHNICAL_FORM_ON_EXECUTOR_S1 on EIS_TECHNICAL_FORM (EXECUTOR_S1_ID);
