alter table EIS_ANALYSIS_FORM add constraint FK_EIS_ANALYSIS_FORM_ON_DEFECT_NATURE foreign key (DEFECT_NATURE_ID) references EIS_DEFECT_NATURE(ID);
create index IDX_EIS_ANALYSIS_FORM_ON_DEFECT_NATURE on EIS_ANALYSIS_FORM (DEFECT_NATURE_ID);
