alter table EIS_TECHNICAL_FORM add constraint FK_EIS_TECHNICAL_FORM_ON_MANUFACTURER foreign key (MANUFACTURER_ID) references EIS_DIVISION_INDEX(ID);
create index IDX_EIS_TECHNICAL_FORM_ON_MANUFACTURER on EIS_TECHNICAL_FORM (MANUFACTURER_ID);
