-- begin EIS_NOMENCLATURE_ITEM
create index IDX_EIS_NOMENCLATURE_ITEM_IDGAL on EIS_NOMENCLATURE_ITEM (IDGAL)^
create index IDX_EIS_NOMENCLATURE_ITEM_NAME on EIS_NOMENCLATURE_ITEM (NAME)^
-- end EIS_NOMENCLATURE_ITEM
