alter table EIS_ANALYSIS_FORM add constraint FK_EIS_ANALYSIS_FORM_ON_CHAIRMAN foreign key (CHAIRMAN_ID) references EIS_EMPLOYEE(ID);
create index IDX_EIS_ANALYSIS_FORM_ON_CHAIRMAN on EIS_ANALYSIS_FORM (CHAIRMAN_ID);
