-- begin EIS_NOMENCLATURE_ITEM
alter table EIS_NOMENCLATURE_ITEM add constraint FK_EIS_NOMENCLATURE_ITEM_ON_UOM foreign key (UOM_ID) references EIS_UNIT_OF_MEASURE(ID)^
create index IDX_EIS_NOMENCLATURE_ITEM_ON_UOM on EIS_NOMENCLATURE_ITEM (UOM_ID)^
create index IDX_EIS_NOMENCLATURE_ITEM_IDGAL on EIS_NOMENCLATURE_ITEM (IDGAL)^
create index IDX_EIS_NOMENCLATURE_ITEM_NAME on EIS_NOMENCLATURE_ITEM (NAME)^
-- end EIS_NOMENCLATURE_ITEM
-- begin EIS_NTK_BOM_ITEM
alter table EIS_NTK_BOM_ITEM add constraint FK_EIS_NTK_BOM_ITEM_ON_COMPONENT foreign key (COMPONENT_ID) references EIS_NOMENCLATURE_ITEM(ID)^
alter table EIS_NTK_BOM_ITEM add constraint FK_EIS_NTK_BOM_ITEM_ON_NTK_ITEM foreign key (NTK_ITEM_ID) references EIS_NTK_ITEM(ID)^
create index IDX_EIS_NTK_BOM_ITEM_ON_COMPONENT on EIS_NTK_BOM_ITEM (COMPONENT_ID)^
create index IDX_EIS_NTK_BOM_ITEM_ON_NTK_ITEM on EIS_NTK_BOM_ITEM (NTK_ITEM_ID)^
-- end EIS_NTK_BOM_ITEM
-- begin EIS_NTK_ITEM
alter table EIS_NTK_ITEM add constraint FK_EIS_NTK_ITEM_ON_COMPONENT foreign key (COMPONENT_ID) references EIS_NOMENCLATURE_ITEM(ID)^
create index IDX_EIS_NTK_ITEM_ON_COMPONENT on EIS_NTK_ITEM (COMPONENT_ID)^
-- end EIS_NTK_ITEM
-- begin EIS_TECHNICAL_FORM
alter table EIS_TECHNICAL_FORM add constraint FK_EIS_TECHNICAL_FORM_ON_COMPONENT foreign key (COMPONENT_ID) references EIS_NOMENCLATURE_ITEM(ID)^
alter table EIS_TECHNICAL_FORM add constraint FK_EIS_TECHNICAL_FORM_ON_PRODUCT foreign key (PRODUCT_ID) references EIS_PRODUCT(ID)^
create index IDX_EIS_TECHNICAL_FORM_ON_COMPONENT on EIS_TECHNICAL_FORM (COMPONENT_ID)^
create index IDX_EIS_TECHNICAL_FORM_ON_PRODUCT on EIS_TECHNICAL_FORM (PRODUCT_ID)^
-- end EIS_TECHNICAL_FORM
-- begin EIS_EMPLOYEE
alter table EIS_EMPLOYEE add constraint FK_EIS_EMPLOYEE_ON_JOB_TITLE foreign key (JOB_TITLE_ID) references EIS_JOB_TITLE(ID)^
create index IDX_EIS_EMPLOYEE_ON_JOB_TITLE on EIS_EMPLOYEE (JOB_TITLE_ID)^
-- end EIS_EMPLOYEE
