alter table EIS_TECHNICAL_FORM add constraint FK_EIS_TECHNICAL_FORM_ON_PRODUCT foreign key (PRODUCT_ID) references EIS_PRODUCT(ID);
create index IDX_EIS_TECHNICAL_FORM_ON_PRODUCT on EIS_TECHNICAL_FORM (PRODUCT_ID);
