alter table EIS_NTK_ITEM add constraint FK_EIS_NTK_ITEM_ON_COMPONENT foreign key (COMPONENT_ID) references EIS_NOMENCLATURE_ITEM(ID);
create index IDX_EIS_NTK_ITEM_ON_COMPONENT on EIS_NTK_ITEM (COMPONENT_ID);
