alter table EIS_DIVISION_INDEX add constraint FK_EIS_DIVISION_INDEX_ON_MASTER foreign key (MASTER_ID) references EIS_DIVISION_INDEX(ID);
create index IDX_EIS_DIVISION_INDEX_ON_MASTER on EIS_DIVISION_INDEX (MASTER_ID);
