alter table EIS_TECHNICAL_FORM add constraint FK_EIS_TECHNICAL_FORM_ON_EXECUTOR_S2 foreign key (EXECUTOR_S2_ID) references EIS_DIVISION_INDEX(ID);
create index IDX_EIS_TECHNICAL_FORM_ON_EXECUTOR_S2 on EIS_TECHNICAL_FORM (EXECUTOR_S2_ID);
