alter table EIS_TECHNICAL_FORM add constraint FK_EIS_TECHNICAL_FORM_ON_COMPONENT foreign key (COMPONENT_ID) references EIS_NOMENCLATURE_ITEM(ID);
create index IDX_EIS_TECHNICAL_FORM_ON_COMPONENT on EIS_TECHNICAL_FORM (COMPONENT_ID);
