alter table EIS_NTK_BOM_ITEM add constraint FK_EIS_NTK_BOM_ITEM_ON_COMPONENT foreign key (COMPONENT_ID) references EIS_NOMENCLATURE_ITEM(ID);
alter table EIS_NTK_BOM_ITEM add constraint FK_EIS_NTK_BOM_ITEM_ON_NTK_ITEM foreign key (NTK_ITEM_ID) references EIS_NTK_ITEM(ID);
create index IDX_EIS_NTK_BOM_ITEM_ON_COMPONENT on EIS_NTK_BOM_ITEM (COMPONENT_ID);
create index IDX_EIS_NTK_BOM_ITEM_ON_NTK_ITEM on EIS_NTK_BOM_ITEM (NTK_ITEM_ID);
